sudo: false
language: php

php:
    - 7.4
    - 8.0
    - nightly

matrix:
    allow_failures:
        - php: nightly

install:
    - composer self-update
    - composer install --no-interaction --no-suggest

script:
    - ./vendor/bin/phpunit  --coverage-clover coverage.xml

after_success:
    - bash <(curl -s https://codecov.io/bash)